name: build-web
on:
  push:
    branches: [ main ]
jobs:
  web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./web
          file: web/Dockerfile
          push: true
          tags: ghcr.io/pet84/dify-web-custom:1.9.1
